### ISSUE TITLE
it is not necessary to create always two function when you wont to call API

### ISSUE THREAD

**Issue by Elias011** [ammarkasem2016/homeWork#3]
`function xmlFunOne () {  
    let url = 'https://api.github.com/orgs/HackYourFuture/repos';
    let xmlHtml = new XMLHttpRequest();
    xmlHtml.open("GET", url, false);
      xmlHtml.onload = function (){
      if (xmlHtml.status === 200 && xmlHtml.readyState === 4){
          let repositories = JSON.parse(xmlHtml.response);
          dataRepos(repositories);
        }
      }    
      xmlHtml.send();
}

function dataRepos (data) {
    for (let i = 0; i < data.length; i++){
        button1.innerHTML += "<ul><li><span>" + "<a href ='" + data[i].html_url+"'>" +  data[i].name + "</a>" + "</span></li></ul>";
    }
}`

 **you can do it in one function like this**

`function xmlFunTwo () {
    let apiLink = 'https://api.github.com/repos/HackYourFuture/';
    let repositoriesName = inPut.value;
    let url = apiLink + repositoriesName;
    let xmlHtml = new XMLHttpRequest();
    xmlHtml.open("GET", url, false);
    xmlHtml.send();
    if (xmlHtml.status == 200 && xmlHtml.readyState === 4){
        let repositories = JSON.parse(xmlHtml.response);   
        search(repositories);
        }
    else {
        alert("Not Found !!!!! Please !!!!! Write Good Repository Name !!!!! Check First Good writing !!!!!")
    }
    
};

function search (data){
        boxFound.innerHTML += "<ul><li><span>" + "Repository Name:  " + data.name + "</li><li>" + "Repository Description:  " + data.description +"</li><li>" + "Stargazers Count:  " + data.stargazers_count + "</li><li>" + "Watchers Count:  " + data.watchers_count + "</li><li>" + " Languag:  " + data.language + "</li><li>" + "Forks:  " + data.forks + "</span></li></ul>";
}`

**Comment by ammarkasem2016** [comment]
i try for this
